[package]
name = "nerd-core"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
authors = ["henry <devgony@gmail.com>"]
description = "The nerdy Entity Relationship Diagram"
license = "Apache-2.0"

[dependencies]
ratatui = "0.28"
crossterm = "0.28"
sqlparser = "0.52"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
insta = { version = "1.40", features = ["yaml"] }
